//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lumina.NotepadDemo.Properties;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources
{
    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources()
    {
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            resourceMan ??= new global::System.Resources.ResourceManager("Lumina.NotepadDemo.Properties.Resources", typeof(Resources).Assembly);
            return resourceMan;
        }
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    internal static string About => ResourceManager.GetString("About", resourceCulture);

    internal static string Color => ResourceManager.GetString("Color", resourceCulture);

    internal static string DateTime => ResourceManager.GetString("DateTime", resourceCulture);

    internal static string EditMenu => ResourceManager.GetString("EditMenu", resourceCulture);

    internal static string Exit => ResourceManager.GetString("Exit", resourceCulture);

    internal static string FileMenu => ResourceManager.GetString("FileMenu", resourceCulture);

    internal static string Find => ResourceManager.GetString("Find", resourceCulture);

    internal static string Font => ResourceManager.GetString("Font", resourceCulture);

    internal static string FormatMenu => ResourceManager.GetString("FormatMenu", resourceCulture);

    internal static string Gitee => ResourceManager.GetString("Gitee", resourceCulture);

    internal static string GitHub => ResourceManager.GetString("GitHub", resourceCulture);

    internal static string HelpMenu => ResourceManager.GetString("HelpMenu", resourceCulture);

    internal static string NewFile => ResourceManager.GetString("NewFile", resourceCulture);

    internal static string OpenFile => ResourceManager.GetString("OpenFile", resourceCulture);

    internal static string OpenFolder => ResourceManager.GetString("OpenFolder", resourceCulture);

    internal static string Replace => ResourceManager.GetString("Replace", resourceCulture);

    internal static string Save => ResourceManager.GetString("Save", resourceCulture);

    internal static string SaveAs => ResourceManager.GetString("SaveAs", resourceCulture);

    internal static string WordCount => ResourceManager.GetString("WordCount", resourceCulture);

    internal static string WrapText => ResourceManager.GetString("WrapText", resourceCulture);
}