//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lumina.NotepadDemo.Properties;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources
{
    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources()
    {
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            resourceMan ??= new global::System.Resources.ResourceManager("Lumina.NotepadDemo.Properties.Resources", typeof(Resources).Assembly);
            return resourceMan;
        }
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    internal static global::System.Drawing.Bitmap About => ((global::System.Drawing.Bitmap)(ResourceManager.GetObject("About", resourceCulture)));

    internal static global::System.Drawing.Bitmap Color => ((global::System.Drawing.Bitmap)(ResourceManager.GetObject("Color", resourceCulture)));

    internal static global::System.Drawing.Bitmap DateTime => ((global::System.Drawing.Bitmap)(ResourceManager.GetObject("DateTime", resourceCulture)));

    internal static global::System.Drawing.Bitmap EditMenu => ((global::System.Drawing.Bitmap)(ResourceManager.GetObject("EditMenu", resourceCulture)));

    internal static global::System.Drawing.Bitmap Exit => ((global::System.Drawing.Bitmap)(ResourceManager.GetObject("Exit", resourceCulture)));

    internal static global::System.Drawing.Bitmap FileMenu => ((global::System.Drawing.Bitmap)(ResourceManager.GetObject("FileMenu", resourceCulture)));

    internal static global::System.Drawing.Bitmap Find => ((global::System.Drawing.Bitmap)(ResourceManager.GetObject("Find", resourceCulture)));

    internal static global::System.Drawing.Bitmap Font => ((global::System.Drawing.Bitmap)(ResourceManager.GetObject("Font", resourceCulture)));

    internal static global::System.Drawing.Bitmap FormatMenu => ((global::System.Drawing.Bitmap)(ResourceManager.GetObject("FormatMenu", resourceCulture)));

    internal static global::System.Drawing.Bitmap Gitee => ((global::System.Drawing.Bitmap)(ResourceManager.GetObject("Gitee", resourceCulture)));

    internal static global::System.Drawing.Bitmap GitHub => ((global::System.Drawing.Bitmap)(ResourceManager.GetObject("GitHub", resourceCulture)));

    internal static global::System.Drawing.Bitmap HelpMenu => ((global::System.Drawing.Bitmap)(ResourceManager.GetObject("HelpMenu", resourceCulture)));

    internal static global::System.Drawing.Bitmap NewFile => ((global::System.Drawing.Bitmap)(ResourceManager.GetObject("NewFile", resourceCulture)));

    internal static global::System.Drawing.Bitmap OpenFile => ((global::System.Drawing.Bitmap)(ResourceManager.GetObject("OpenFile", resourceCulture)));

    internal static global::System.Drawing.Bitmap OpenFolder => ((global::System.Drawing.Bitmap)(ResourceManager.GetObject("OpenFolder", resourceCulture)));

    internal static global::System.Drawing.Bitmap Replace => ((global::System.Drawing.Bitmap)(ResourceManager.GetObject("Replace", resourceCulture)));

    internal static global::System.Drawing.Bitmap Save => ((global::System.Drawing.Bitmap)(ResourceManager.GetObject("Save", resourceCulture)));

    internal static global::System.Drawing.Bitmap SaveAs => ((global::System.Drawing.Bitmap)(ResourceManager.GetObject("SaveAs", resourceCulture)));

    internal static global::System.Drawing.Bitmap WordCount => ((global::System.Drawing.Bitmap)(ResourceManager.GetObject("WordCount", resourceCulture)));

    internal static global::System.Drawing.Bitmap WrapText => ((global::System.Drawing.Bitmap)(ResourceManager.GetObject("WrapText", resourceCulture)));
}