//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lumina.NotepadDemo.Properties;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources
{
    private static global::System.Resources.ResourceManager? resourceMan;

    private static global::System.Globalization.CultureInfo? resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources()
    {
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            resourceMan ??= new global::System.Resources.ResourceManager("Lumina.NotepadDemo.Properties.Resources", typeof(Resources).Assembly);
            return resourceMan;
        }
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    internal static global::System.Drawing.Icon About => ((global::System.Drawing.Icon)(ResourceManager.GetObject("About", resourceCulture)!));

    internal static global::System.Drawing.Icon Color => ((global::System.Drawing.Icon)(ResourceManager.GetObject("Color", resourceCulture)!));

    internal static global::System.Drawing.Icon DateTime => ((global::System.Drawing.Icon)(ResourceManager.GetObject("DateTime", resourceCulture)!));

    internal static global::System.Drawing.Icon EditMenu => ((global::System.Drawing.Icon)(ResourceManager.GetObject("EditMenu", resourceCulture)!));

    internal static global::System.Drawing.Icon Exit => ((global::System.Drawing.Icon)(ResourceManager.GetObject("Exit", resourceCulture)!));

    internal static global::System.Drawing.Icon FileMenu => ((global::System.Drawing.Icon)(ResourceManager.GetObject("FileMenu", resourceCulture)!));

    internal static global::System.Drawing.Icon Find => ((global::System.Drawing.Icon)(ResourceManager.GetObject("Find", resourceCulture)!));

    internal static global::System.Drawing.Icon Font => ((global::System.Drawing.Icon)(ResourceManager.GetObject("Font", resourceCulture)!));

    internal static global::System.Drawing.Icon FormatMenu => ((global::System.Drawing.Icon)(ResourceManager.GetObject("FormatMenu", resourceCulture)!));

    internal static global::System.Drawing.Icon Gitee => ((global::System.Drawing.Icon)(ResourceManager.GetObject("Gitee", resourceCulture)!));

    internal static global::System.Drawing.Icon GitHub => ((global::System.Drawing.Icon)(ResourceManager.GetObject("GitHub", resourceCulture)!));

    internal static global::System.Drawing.Icon HelpMenu => ((global::System.Drawing.Icon)(ResourceManager.GetObject("HelpMenu", resourceCulture)!));

    internal static global::System.Drawing.Icon NewFile => ((global::System.Drawing.Icon)(ResourceManager.GetObject("NewFile", resourceCulture)!));

    internal static global::System.Drawing.Icon OpenFile => ((global::System.Drawing.Icon)(ResourceManager.GetObject("OpenFile", resourceCulture)!));

    internal static global::System.Drawing.Icon OpenFolder => ((global::System.Drawing.Icon)(ResourceManager.GetObject("OpenFolder", resourceCulture)!));

    internal static global::System.Drawing.Icon Replace => ((global::System.Drawing.Icon)(ResourceManager.GetObject("Replace", resourceCulture)!));

    internal static global::System.Drawing.Icon Save => ((global::System.Drawing.Icon)(ResourceManager.GetObject("Save", resourceCulture)!));

    internal static global::System.Drawing.Icon SaveAs => ((global::System.Drawing.Icon)(ResourceManager.GetObject("SaveAs", resourceCulture)!));

    internal static global::System.Drawing.Icon WordCount => ((global::System.Drawing.Icon)(ResourceManager.GetObject("WordCount", resourceCulture)!));

    internal static global::System.Drawing.Icon WrapText => ((global::System.Drawing.Icon)(ResourceManager.GetObject("WrapText", resourceCulture)!));
}