<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TargetFramework>net10.0</TargetFramework>
    <PublishAot>true</PublishAot>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>true</PublishTrimmed>
    <CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
    <PublishDocumentationFile>false</PublishDocumentationFile>
    <PublishReferencesDocumentationFiles>false</PublishReferencesDocumentationFiles>
    <UseLuminaForms>true</UseLuminaForms>
    <CustomResourceTypesSupport>true</CustomResourceTypesSupport>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <ApplicationIcon Condition="'$(ApplicationIcon)' == ''">Resources\lumina-tray.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lumina.Core\Lumina.Core.csproj" />
    <ProjectReference Include="..\Lumina.Forms\Lumina.Forms.csproj" />
    <ProjectReference Include="..\Lumina.Forms.Analyzers\Lumina.Forms.Analyzers.csproj" />
    <Using Include="Lumina.Forms" />
    <Using Include="System.Drawing" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" Version="10.0.5" />
  </ItemGroup>

  <Target Name="CleanPublishAuxiliaryFiles" AfterTargets="Publish">
    <ItemGroup>
      <PublishAuxiliaryFiles Include="$(PublishDir)**\*.pdb" />
      <PublishAuxiliaryFiles Include="$(PublishDir)**\*.xml" />
    </ItemGroup>
    <Delete Files="@(PublishAuxiliaryFiles)" />
  </Target>

  <Target Name="ExcludeAuxiliaryFilesFromPublish" BeforeTargets="ComputeFilesToPublish">
    <ItemGroup>
      <ResolvedFileToPublish Remove="@(ResolvedFileToPublish)" Condition="'%(ResolvedFileToPublish.Extension)' == '.pdb'" />
      <ResolvedFileToPublish Remove="@(ResolvedFileToPublish)" Condition="'%(ResolvedFileToPublish.Extension)' == '.xml'" />
    </ItemGroup>
  </Target>

</Project>
